[package]
name = "nbv-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "nvb"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
nbv-tui = { version = "0.1.0", path = "../nbv-tui" }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
serde_json.workspace = true
tempfile = "3"
