[package]
name = "nbv-nvim"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait = "0.1"
nbv-core = { version = "0.1.0", path = "../nbv-core" }
nvim-rs = { version = "0.9", features = ["use_tokio"] }
rmpv = "1"
thiserror = "2"
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
serde_json = "1"
tempfile = "3"
